### ISSUE TITLE
No or wrong information displayed after click at "?"

### ISSUE THREAD

**Issue by wendy2702** [Apollon77/ioBroker.smartmeter#11]
Hi,

as allready shown here:

https://forum.iobroker.net/viewtopic.php?f=23&t=5047&p=141823#p141814

![smartmeter_info](https://user-images.githubusercontent.com/33424168/38673873-d54bcbde-3e52-11e8-8510-dc85bb7f166b.jpg)

![anderungsprotokoll](https://user-images.githubusercontent.com/33424168/38673877-daa7cd30-3e52-11e8-8fea-58fa2dffb345.jpg)

No or wrong information is shown for Adapter.

Br

**Comment by Apollon77** [comment]
please update to latest version and retest

**Comment by Apollon77** [comment]
Do you also updated the adapter on all machines where it is installed?

**Comment by wendy2702** [comment]
Adapter is only installed at one Slave which is called: PI-IOBROKER as you can see from attached screenshots above.

**Comment by wendy2702** [comment]
Sorry, my mistake. Did not select the correct HOST while installingg Smartmeter Adapter from GIT.

Now i have to figure out how to delete the Adapter from Host only.

**Comment by Apollon77** [comment]
Commandline 

npm uninstall iobroker.smartmeter
