### ISSUE TITLE
Landis & Gyr E220 erfolgreich eingebunden

### ISSUE THREAD

**Issue by MMeinhardt1** [Apollon77/ioBroker.smartmeter#116]
Hi,

ich habe einen Landis & Gyr E220 nach Eingabe des PIN und freischalten der erweiterten Info Schnittstelle erfolgreich in den Smartmeter Adapter einbinden können.
Das ganze funktioniert sehr gut und zuverlässig!

Danke

**Comment by snookerap** [comment]
Hi, mit welchen Einstellungen im Adapter hast du den E220 zum Laufen gebracht.
Habe eine E320, der sieht identisch wie der E220 aus.
Eventuell läuft der ja auch mit deinen Einstellungen.

Danke im voraus

**Comment by MMeinhardt1** [comment]
Hi @snookerap 
hier ein Bild meiner Einstellungen, vielleicht hilft es dir. 

![image](https://user-images.githubusercontent.com/56205459/161414056-d6053175-a63d-4788-bc51-f0b52ed076cd.jpeg)

**Comment by snookerap** [comment]
mhh.. danke ...

Leider funzt es damit auch nicht, denke meiner muss freigeschaltet sein.
Gestatte mir nch eine Frage... :-)

Wie hast du den freigeschaltet, muss das vom Netzbetreiber passieren?
Die PIN habe ich, ins Menü komme ich auch rein.

Dank für deine Mühe

**Comment by MMeinhardt1** [comment]
Hi,
du musst den PIN eingeben und InF freischalten, dass sind die erweiterten Daten. Lies dir das Manual aus dem oberen Link mal durch, insbesondere ab Seite 27, dort wirst du fündig und dann wird es bestimmt auch klappen.
