### ISSUE TITLE
DWS7412.2 Zähler werte unter 650W werden als Minus angezeigt

### ISSUE THREAD

**Issue by Jetiman** [Apollon77/ioBroker.smartmeter#128]
MoinMoin,

ich habe ein Problem bei einem Zähler, die anderen vorhandenen Zähler funktionieren. Einer wurde aber erneuert durch den DWS 7412.2.
Wenn der Wert am Zähler unter 650W geht werden im Broker Minus werte angezeigt.

Als Beispiel:
Zähler 582W
Broker -94.41W

Als Einstellungen nutze ich:
60S Abfrageintervall
Daten nur Lesen
SML 1.0.3
Baud 9600

Den Rest habe ich Standard gelassen.

**Comment by Apollon77** [comment]
Bitte vollständige SML Nachricht (Debug log aktivieren und so eine holen) und idealerweise Logging bereitstellen. Dann muss man sehen. CHance auf nen Firmware Bug im gerät ist snicht schlecht ... wurde auch bei FHEM berichtet (https://forum.fhem.de/index.php/topic,51948.msg834274.html#msg834274)

**Comment by Apollon77** [comment]
Und du bist sicher das negativ nicht irgendwie einspeisung oder so bedeutet ?!

**Comment by Jetiman** [comment]
Log kommt noch. Einspeisung habe ich nicht.

**Comment by Jetiman** [comment]
Ich hoffe damit kann man etwas anfangen.


`smartmeter.0	2020-07-19 20:26:23.757	debug	(26076) SERIALPORT CLOSE
smartmeter.0	2020-07-19 20:26:23.725	debug	(26076) SCHEDULE NEXT RUN IN 30s
smartmeter.0	2020-07-19 20:26:23.723	debug	(26076) RESUME READING SERIALPORT
smartmeter.0	2020-07-19 20:26:23.721	debug	(26076) SET MESSAGE TIMEOUT TIMER: 120000
smartmeter.0	2020-07-19 20:26:23.719	info	(26076) Received 5 values, 2 updated
smartmeter.0	2020-07-19 20:26:23.717	debug	(26076) Set State 1-0:16_7_0__255.value = 5226.49
smartmeter.0	2020-07-19 20:26:23.714	debug	(26076) Set State 1-0:16_7_0__255.rawvalue = undefined
smartmeter.0	2020-07-19 20:26:23.713	debug	(26076) 1-0:16.7.0*255: Momentanwert Gesamtwirkleistung (Total) = 5226.49 W
smartmeter.0	2020-07-19 20:26:23.710	debug	(26076) Data for 1-0:2_8_0__255 unchanged
smartmeter.0	2020-07-19 20:26:23.708	debug	(26076) 1-0:2.8.0*255: Zählerstand 1 Summe Wirkarbeit Abgabe - (Total) = 0 kWh
smartmeter.0	2020-07-19 20:26:23.706	debug	(26076) Set State 1-0:1_8_0__255.value = 16718.478
smartmeter.0	2020-07-19 20:26:23.703	debug	(26076) Set State 1-0:1_8_0__255.rawvalue = undefined
smartmeter.0	2020-07-19 20:26:23.702	debug	(26076) 1-0:1.8.0*255: Zählerstand 1 Summe Wirkarbeit Bezug + (Total) = 16718.478 kWh
smartmeter.0	2020-07-19 20:26:23.700	debug	(26076) Data for 1-0:96_1_0__255 unchanged
smartmeter.0	2020-07-19 20:26:23.699	debug	(26076) 1-0:96.1.0*255: Serialnumber = 0a01445a47000282526b
smartmeter.0	2020-07-19 20:26:23.697	debug	(26076) Data for 1-0:96_50_1__1 unchanged
smartmeter.0	2020-07-19 20:26:23.695	debug	(26076) 1-0:96.50.1*1: Wartungseintrag (T1) letztes Jahr = DZG
smartmeter.0	2020-07-19 20:26:23.694	debug	(26076) STORE DATA
smartmeter.0	2020-07-19 20:26:23.691	debug	(26076) SML MESSAGE: START SML-File START SmlMessage Transaction-ID: S� (0a53e00a) Group-No: 0 Abort On Error: 0 Message-Body: SmlPublicOpenResponse Codepage: undefined Client-ID: u
smartmeter.0	2020-07-19 20:26:23.686	debug	(26076) MSG IDX 2
smartmeter.0	2020-07-19 20:26:23.685	debug	(26076) PAUSE READING SERIALPORT TO HANDLE MESSAGE
smartmeter.0	2020-07-19 20:26:23.683	debug	(26076) MATCH-RESULT MESSAGE: "241b1b1b1b0101010176050a53e00a620062007263010176010102310b0a01445a47000282526b7262016503ac4851620263eb2c0076050b53e00a620062007263070177010b0a01445a47000282526b070100620
smartmeter.0	2020-07-19 20:26:23.681	debug	(26076) ADD NEW DATA (250 + NEW 7)
smartmeter.0	2020-07-19 20:26:23.667	debug	(26076) MATCH-RESULT MESSAGE: "241b1b1b1b0101010176050a53e00a620062007263010176010102310b0a01445a47000282526b7262016503ac4851620263eb2c0076050b53e00a620062007263070177010b0a01445a47000282526b070100620
smartmeter.0	2020-07-19 20:26:23.665	debug	(26076) ADD NEW DATA (236 + NEW 14)
smartmeter.0	2020-07-19 20:26:23.651	debug	(26076) MATCH-RESULT MESSAGE: "241b1b1b1b0101010176050a53e00a620062007263010176010102310b0a01445a47000282526b7262016503ac4851620263eb2c0076050b53e00a620062007263070177010b0a01445a47000282526b070100620
smartmeter.0	2020-07-19 20:26:23.649	debug	(26076) ADD NEW DATA (222 + NEW 14)
smartmeter.0	2020-07-19 20:26:23.635	debug	(26076) MATCH-RESULT MESSAGE: "241b1b1b1b0101010176050a53e00a620062007263010176010102310b0a01445a47000282526b7262016503ac4851620263eb2c0076050b53e00a620062007263070177010b0a01445a47000282526b070100620
smartmeter.0	2020-07-19 20:26:23.633	debug	(26076) ADD NEW DATA (208 + NEW 14)
smartmeter.0	2020-07-19 20:26:23.619	debug	(26076) MATCH-RESULT MESSAGE: "241b1b1b1b0101010176050a53e00a620062007263010176010102310b0a01445a47000282526b7262016503ac4851620263eb2c0076050b53e00a620062007263070177010b0a01445a47000282526b070100620
smartmeter.0	2020-07-19 20:26:23.617	debug	(26076) ADD NEW DATA (194 + NEW 14)
smartmeter.0	2020-07-19 20:26:23.603	debug	(26076) MATCH-RESULT MESSAGE: "241b1b1b1b0101010176050a53e00a620062007263010176010102310b0a01445a47000282526b7262016503ac4851620263eb2c0076050b53e00a620062007263070177010b0a01445a47000282526b070100620
smartmeter.0	2020-07-19 20:26:23.601	debug	(26076) ADD NEW DATA (181 + NEW 13)
smartmeter.0	2020-07-19 20:26:23.587	debug	(26076) MATCH-RESULT MESSAGE: "241b1b1b1b0101010176050a53e00a620062007263010176010102310b0a01445a47000282526b7262016503ac4851620263eb2c0076050b53e00a620062007263070177010b0a01445a47000282526b070100620
smartmeter.0	2020-07-19 20:26:23.585	debug	(26076) ADD NEW DATA (167 + NEW 14)
smartmeter.0	2020-07-19 20:26:23.571	debug	(26076) MATCH-RESULT MESSAGE: "241b1b1b1b0101010176050a53e00a620062007263010176010102310b0a01445a47000282526b7262016503ac4851620263eb2c0076050b53e00a620062007263070177010b0a01445a47000282526b070100620
smartmeter.0	2020-07-19 20:26:23.569	debug	(26076) ADD NEW DATA (153 + NEW 14)
smartmeter.0	2020-07-19 20:26:23.555	debug	(26076) MATCH-RESULT MESSAGE: "241b1b1b1b0101010176050a53e00a620062007263010176010102310b0a01445a47000282526b7262016503ac4851620263eb2c0076050b53e00a620062007263070177010b0a01445a47000282526b070100620
smartmeter.0	2020-07-19 20:26:23.553	debug	(26076) ADD NEW DATA (139 + NEW 14)
smartmeter.0	2020-07-19 20:26:23.539	debug	(26076) MATCH-RESULT MESSAGE: "241b1b1b1b0101010176050a53e00a620062007263010176010102310b0a01445a47000282526b7262016503ac4851620263eb2c0076050b53e00a620062007263070177010b0a01445a47000282526b070100620
smartmeter.0	2020-07-19 20:26:23.537	debug	(26076) ADD NEW DATA (125 + NEW 14)
smartmeter.0	2020-07-19 20:26:23.523	debug	(26076) MATCH-RESULT MESSAGE: "241b1b1b1b0101010176050a53e00a620062007263010176010102310b0a01445a47000282526b7262016503ac4851620263eb2c0076050b53e00a620062007263070177010b0a01445a47000282526b070100620
smartmeter.0	2020-07-19 20:26:23.521	debug	(26076) ADD NEW DATA (111 + NEW 14)
smartmeter.0	2020-07-19 20:26:23.507	debug	(26076) MATCH-RESULT MESSAGE: "241b1b1b1b0101010176050a53e00a620062007263010176010102310b0a01445a47000282526b7262016503ac4851620263eb2c0076050b53e00a620062007263070177010b0a01445a47000282526b070100620
smartmeter.0	2020-07-19 20:26:23.505	debug	(26076) ADD NEW DATA (97 + NEW 14)
smartmeter.0	2020-07-19 20:26:23.491	debug	(26076) MATCH-RESULT MESSAGE: "241b1b1b1b0101010176050a53e00a620062007263010176010102310b0a01445a47000282526b7262016503ac4851620263eb2c0076050b53e00a620062007263070177010b0a01445a47000282526b070100620
smartmeter.0	2020-07-19 20:26:23.489	debug	(26076) ADD NEW DATA (83 + NEW 14)
smartmeter.0	2020-07-19 20:26:23.480	debug	(26076) MATCH-RESULT MESSAGE: "241b1b1b1b0101010176050a53e00a620062007263010176010102310b0a01445a47000282526b7262016503ac4851620263eb2c0076050b53e00a620062007263070177010b0a01445a47000282526b070100" -
smartmeter.0	2020-07-19 20:26:23.478	debug	(26076) ADD NEW DATA (69 + NEW 14)
smartmeter.0	2020-07-19 20:26:23.469	debug	(26076) MATCH-RESULT MESSAGE: "241b1b1b1b0101010176050a53e00a620062007263010176010102310b0a01445a47000282526b7262016503ac4851620263eb2c0076050b53e00a62006200726307017701" -> null
smartmeter.0	2020-07-19 20:26:23.466	debug	(26076) ADD NEW DATA (55 + NEW 14)
smartmeter.0	2020-07-19 20:26:23.451	debug	(26076) MATCH-RESULT MESSAGE: "241b1b1b1b0101010176050a53e00a620062007263010176010102310b0a01445a47000282526b7262016503ac4851620263eb2c007605" -> null
smartmeter.0	2020-07-19 20:26:23.448	debug	(26076) ADD NEW DATA (41 + NEW 14)
smartmeter.0	2020-07-19 20:26:23.428	debug	(26076) MATCH-RESULT MESSAGE: "241b1b1b1b0101010176050a53e00a620062007263010176010102310b0a01445a47000282526b7262" -> null
smartmeter.0	2020-07-19 20:26:23.425	debug	(26076) ADD NEW DATA (27 + NEW 14)
smartmeter.0	2020-07-19 20:26:23.412	debug	(26076) MATCH-RESULT MESSAGE: "241b1b1b1b0101010176050a53e00a620062007263010176010102" -> null
smartmeter.0	2020-07-19 20:26:23.409	debug	(26076) ADD NEW DATA (13 + NEW 14)
smartmeter.0	2020-07-19 20:26:23.396	debug	(26076) MATCH-RESULT MESSAGE: "241b1b1b1b0101010176050a53" -> null
smartmeter.0	2020-07-19 20:26:23.394	debug	(26076) ADD NEW DATA (0 + NEW 13)
smartmeter.0	2020-07-19 20:26:23.384	debug	(26076) SET MESSAGE TIMEOUT TIMER: 120000
smartmeter.0	2020-07-19 20:26:23.378	debug	(26076) SERIALPORT OPEN
smartmeter.0	2020-07-19 20:25:53.407	debug	(26076) SERIALPORT CLOSE
smartmeter.0	2020-07-19 20:25:53.374	debug	(26076) SCHEDULE NEXT RUN IN 30s
smartmeter.0	2020-07-19 20:25:53.372	debug	(26076) RESUME READING SERIALPORT
smartmeter.0	2020-07-19 20:25:53.370	debug	(26076) SET MESSAGE TIMEOUT TIMER: 120000
smartmeter.0	2020-07-19 20:25:53.368	info	(26076) Received 5 values, 2 updated
smartmeter.0	2020-07-19 20:25:53.365	debug	(26076) Set State 1-0:16_7_0__255.value = -59.96
smartmeter.0	2020-07-19 20:25:53.363	debug	(26076) Set State 1-0:16_7_0__255.rawvalue = undefined
smartmeter.0	2020-07-19 20:25:53.361	debug	(26076) 1-0:16.7.0*255: Momentanwert Gesamtwirkleistung (Total) = -59.96 W
smartmeter.0	2020-07-19 20:25:53.359	debug	(26076) Data for 1-0:2_8_0__255 unchanged
smartmeter.0	2020-07-19 20:25:53.356	debug	(26076) 1-0:2.8.0*255: Zählerstand 1 Summe Wirkarbeit Abgabe - (Total) = 0 kWh
smartmeter.0	2020-07-19 20:25:53.353	debug	(26076) Set State 1-0:1_8_0__255.value = 16718.4514
smartmeter.0	2020-07-19 20:25:53.351	debug	(26076) Set State 1-0:1_8_0__255.rawvalue = undefined
smartmeter.0	2020-07-19 20:25:53.349	debug	(26076) 1-0:1.8.0*255: Zählerstand 1 Summe Wirkarbeit Bezug + (Total) = 16718.4514 kWh
smartmeter.0	2020-07-19 20:25:53.348	debug	(26076) Data for 1-0:96_1_0__255 unchanged
smartmeter.0	2020-07-19 20:25:53.346	debug	(26076) 1-0:96.1.0*255: Serialnumber = 0a01445a47000282526b
smartmeter.0	2020-07-19 20:25:53.344	debug	(26076) Data for 1-0:96_50_1__1 unchanged
smartmeter.0	2020-07-19 20:25:53.343	debug	(26076) 1-0:96.50.1*1: Wartungseintrag (T1) letztes Jahr = DZG
smartmeter.0	2020-07-19 20:25:53.341	debug	(26076) STORE DATA
smartmeter.0	2020-07-19 20:25:53.338	debug	(26076) SML MESSAGE: START SML-File START SmlMessage Transaction-ID: �R� (b052e00a) Group-No: 0 Abort On Error: 0 Message-Body: SmlPublicOpenResponse Codepage: undefined Client-ID: u
smartmeter.0	2020-07-19 20:25:53.334	debug	(26076) MSG IDX 452
smartmeter.0	2020-07-19 20:25:53.332	debug	(26076) PAUSE READING SERIALPORT TO HANDLE MESSAGE
smartmeter.0	2020-07-19 20:25:53.330	debug	(26076) MATCH-RESULT MESSAGE: "445a47000282526b7262016503ac4832620263b419007605ae52e00a620062007263070177010b0a01445a47000282526b070100620affff7262016503ac483275770701006032010101726201620062005200044
smartmeter.0	2020-07-19 20:25:53.328	debug	(26076) ADD NEW DATA (479 + NEW 3)
smartmeter.0	2020-07-19 20:25:53.314	debug	(26076) MATCH-RESULT MESSAGE: "445a47000282526b7262016503ac4832620263b419007605ae52e00a620062007263070177010b0a01445a47000282526b070100620affff7262016503ac483275770701006032010101726201620062005200044
smartmeter.0	2020-07-19 20:25:53.312	debug	(26076) ADD NEW DATA (465 + NEW 14)
smartmeter.0	2020-07-19 20:25:53.298	debug	(26076) MATCH-RESULT MESSAGE: "445a47000282526b7262016503ac4832620263b419007605ae52e00a620062007263070177010b0a01445a47000282526b070100620affff7262016503ac483275770701006032010101726201620062005200044
smartmeter.0	2020-07-19 20:25:53.296	debug	(26076) ADD NEW DATA (451 + NEW 14)
smartmeter.0	2020-07-19 20:25:53.282	debug	(26076) MATCH-RESULT MESSAGE: "445a47000282526b7262016503ac4832620263b419007605ae52e00a620062007263070177010b0a01445a47000282526b070100620affff7262016503ac483275770701006032010101726201620062005200044
smartmeter.0	2020-07-19 20:25:53.280	debug	(26076) ADD NEW DATA (437 + NEW 14)
smartmeter.0	2020-07-19 20:25:53.267	debug	(26076) MATCH-RESULT MESSAGE: "445a47000282526b7262016503ac4832620263b419007605ae52e00a620062007263070177010b0a01445a47000282526b070100620affff7262016503ac483275770701006032010101726201620062005200044
smartmeter.0	2020-07-19 20:25:53.264	debug	(26076) ADD NEW DATA (423 + NEW 14)
smartmeter.0	2020-07-19 20:25:53.250	debug	(26076) MATCH-RESULT MESSAGE: "445a47000282526b7262016503ac4832620263b419007605ae52e00a620062007263070177010b0a01445a47000282526b070100620affff7262016503ac483275770701006032010101726201620062005200044
smartmeter.0	2020-07-19 20:25:53.248	debug	(26076) ADD NEW DATA (409 + NEW 14)
smartmeter.0	2020-07-19 20:25:53.234	debug	(26076) MATCH-RESULT MESSAGE: "445a47000282526b7262016503ac4832620263b419007605ae52e00a620062007263070177010b0a01445a47000282526b070100620affff7262016503ac483275770701006032010101726201620062005200044
smartmeter.0	2020-07-19 20:25:53.232	debug	(26076) ADD NEW DATA (395 + NEW 14)
smartmeter.0	2020-07-19 20:25:53.218	debug	(26076) MATCH-RESULT MESSAGE: "445a47000282526b7262016503ac4832620263b419007605ae52e00a620062007263070177010b0a01445a47000282526b070100620affff7262016503ac483275770701006032010101726201620062005200044
smartmeter.0	2020-07-19 20:25:53.216	debug	(26076) ADD NEW DATA (381 + NEW 14)
smartmeter.0	2020-07-19 20:25:53.202	debug	(26076) MATCH-RESULT MESSAGE: "445a47000282526b7262016503ac4832620263b419007605ae52e00a620062007263070177010b0a01445a47000282526b070100620affff7262016503ac483275770701006032010101726201620062005200044
smartmeter.0	2020-07-19 20:25:53.200	debug	(26076) ADD NEW DATA (367 + NEW 14)
smartmeter.0	2020-07-19 20:25:53.187	debug	(26076) MATCH-RESULT MESSAGE: "445a47000282526b7262016503ac4832620263b419007605ae52e00a620062007263070177010b0a01445a47000282526b070100620affff7262016503ac483275770701006032010101726201620062005200044
smartmeter.0	2020-07-19 20:25:53.184	debug	(26076) ADD NEW DATA (353 + NEW 14)
smartmeter.0	2020-07-19 20:25:53.170	debug	(26076) MATCH-RESULT MESSAGE: "445a47000282526b7262016503ac4832620263b419007605ae52e00a620062007263070177010b0a01445a47000282526b070100620affff7262016503ac483275770701006032010101726201620062005200044
smartmeter.0	2020-07-19 20:25:53.168	debug	(26076) ADD NEW DATA (339 + NEW 14)
smartmeter.0	2020-07-19 20:25:53.154	debug	(26076) MATCH-RESULT MESSAGE: "445a47000282526b7262016503ac4832620263b419007605ae52e00a620062007263070177010b0a01445a47000282526b070100620affff7262016503ac483275770701006032010101726201620062005200044
smartmeter.0	2020-07-19 20:25:53.152	debug	(26076) ADD NEW DATA (325 + NEW 14)
smartmeter.0	2020-07-19 20:25:53.138	debug	(26076) MATCH-RESULT MESSAGE: "445a47000282526b7262016503ac4832620263b419007605ae52e00a620062007263070177010b0a01445a47000282526b070100620affff7262016503ac483275770701006032010101726201620062005200044
smartmeter.0	2020-07-19 20:25:53.136	debug	(26076) ADD NEW DATA (311 + NEW 14)
smartmeter.0	2020-07-19 20:25:53.122	debug	(26076) MATCH-RESULT MESSAGE: "445a47000282526b7262016503ac4832620263b419007605ae52e00a620062007263070177010b0a01445a47000282526b070100620affff7262016503ac483275770701006032010101726201620062005200044
smartmeter.0	2020-07-19 20:25:53.120	debug	(26076) ADD NEW DATA (297 + NEW 14)
smartmeter.0	2020-07-19 20:25:53.106	debug	(26076) MATCH-RESULT MESSAGE: "445a47000282526b7262016503ac4832620263b419007605ae52e00a620062007263070177010b0a01445a47000282526b070100620affff7262016503ac483275770701006032010101726201620062005200044
smartmeter.0	2020-07-19 20:25:53.104	debug	(26076) ADD NEW DATA (283 + NEW 14)
smartmeter.0	2020-07-19 20:25:53.092	debug	(26076) MATCH-RESULT MESSAGE: "445a47000282526b7262016503ac4832620263b419007605ae52e00a620062007263070177010b0a01445a47000282526b070100620affff7262016503ac483275770701006032010101726201620062005200044
smartmeter.0	2020-07-19 20:25:53.089	debug	(26076) ADD NEW DATA (269 + NEW 14)
smartmeter.0	2020-07-19 20:25:53.076	debug	(26076) MATCH-RESULT MESSAGE: "445a47000282526b7262016503ac4832620263b419007605ae52e00a620062007263070177010b0a01445a47000282526b070100620affff7262016503ac483275770701006032010101726201620062005200044
smartmeter.0	2020-07-19 20:25:53.073	debug	(26076) ADD NEW DATA (255 + NEW 14)
smartmeter.0	2020-07-19 20:25:53.060	debug	(26076) MATCH-RESULT MESSAGE: "445a47000282526b7262016503ac4832620263b419007605ae52e00a620062007263070177010b0a01445a47000282526b070100620affff7262016503ac483275770701006032010101726201620062005200044
smartmeter.0	2020-07-19 20:25:53.057	debug	(26076) ADD NEW DATA (241 + NEW 14)
smartmeter.0	2020-07-19 20:25:53.045	debug	(26076) MATCH-RESULT MESSAGE: "445a47000282526b7262016503ac4832620263b419007605ae52e00a620062007263070177010b0a01445a47000282526b070100620affff7262016503ac483275770701006032010101726201620062005200044
smartmeter.0	2020-07-19 20:25:53.042	debug	(26076) ADD NEW DATA (227 + NEW 14)
smartmeter.0	2020-07-19 20:25:53.028	debug	(26076) MATCH-RESULT MESSAGE: "445a47000282526b7262016503ac4832620263b419007605ae52e00a620062007263070177010b0a01445a47000282526b070100620affff7262016503ac483275770701006032010101726201620062005200044
smartmeter.0	2020-07-19 20:25:53.025	debug	(26076) ADD NEW DATA (226 + NEW 1)
smartmeter.0	2020-07-19 20:25:52.322	debug	(26076) MATCH-RESULT MESSAGE: "445a47000282526b7262016503ac4832620263b419007605ae52e00a620062007263070177010b0a01445a47000282526b070100620affff7262016503ac483275770701006032010101726201620062005200044
smartmeter.0	2020-07-19 20:25:52.320	debug	(26076) ADD NEW DATA (224 + NEW 2)
smartmeter.0	2020-07-19 20:25:52.311	debug	(26076) MATCH-RESULT MESSAGE: "445a47000282526b7262016503ac4832620263b419007605ae52e00a620062007263070177010b0a01445a47000282526b070100620affff7262016503ac483275770701006032010101726201620062005200044
smartmeter.0	2020-07-19 20:25:52.308	debug	(26076) ADD NEW DATA (196 + NEW 28)
smartmeter.0	2020-07-19 20:25:52.274	debug	(26076) MATCH-RESULT MESSAGE: "445a47000282526b7262016503ac4832620263b419007605ae52e00a620062007263070177010b0a01445a47000282526b070100620affff7262016503ac483275770701006032010101726201620062005200044
smartmeter.0	2020-07-19 20:25:52.272	debug	(26076) ADD NEW DATA (182 + NEW 14)
smartmeter.0	2020-07-19 20:25:52.258	debug	(26076) MATCH-RESULT MESSAGE: "445a47000282526b7262016503ac4832620263b419007605ae52e00a620062007263070177010b0a01445a47000282526b070100620affff7262016503ac483275770701006032010101726201620062005200044
smartmeter.0	2020-07-19 20:25:52.256	debug	(26076) ADD NEW DATA (168 + NEW 14)
smartmeter.0	2020-07-19 20:25:52.242	debug	(26076) MATCH-RESULT MESSAGE: "445a47000282526b7262016503ac4832620263b419007605ae52e00a620062007263070177010b0a01445a47000282526b070100620affff7262016503ac483275770701006032010101726201620062005200044
smartmeter.0	2020-07-19 20:25:52.240	debug	(26076) ADD NEW DATA (154 + NEW 14)
smartmeter.0	2020-07-19 20:25:52.227	debug	(26076) MATCH-RESULT MESSAGE: "445a47000282526b7262016503ac4832620263b419007605ae52e00a620062007263070177010b0a01445a47000282526b070100620affff7262016503ac483275770701006032010101726201620062005200044
smartmeter.0	2020-07-19 20:25:52.224	debug	(26076) ADD NEW DATA (140 + NEW 14)
smartmeter.0	2020-07-19 20:25:52.210	debug	(26076) MATCH-RESULT MESSAGE: "445a47000282526b7262016503ac4832620263b419007605ae52e00a620062007263070177010b0a01445a47000282526b070100620affff7262016503ac483275770701006032010101726201620062005200044
smartmeter.0	2020-07-19 20:25:52.208	debug	(26076) ADD NEW DATA (126 + NEW 14)
smartmeter.0	2020-07-19 20:25:52.194	debug	(26076) MATCH-RESULT MESSAGE: "445a47000282526b7262016503ac4832620263b419007605ae52e00a620062007263070177010b0a01445a47000282526b070100620affff7262016503ac483275770701006032010101726201620062005200044
smartmeter.0	2020-07-19 20:25:52.192	debug	(26076) ADD NEW DATA (112 + NEW 14)
smartmeter.0	2020-07-19 20:25:52.178	debug	(26076) MATCH-RESULT MESSAGE: "445a47000282526b7262016503ac4832620263b419007605ae52e00a620062007263070177010b0a01445a47000282526b070100620affff7262016503ac483275770701006032010101726201620062005200044
smartmeter.0	2020-07-19 20:25:52.176	debug	(26076) ADD NEW DATA (98 + NEW 14)
smartmeter.0	2020-07-19 20:25:52.162	debug	(26076) MATCH-RESULT MESSAGE: "445a47000282526b7262016503ac4832620263b419007605ae52e00a620062007263070177010b0a01445a47000282526b070100620affff7262016503ac483275770701006032010101726201620062005200044
smartmeter.0	2020-07-19 20:25:52.160	debug	(26076) ADD NEW DATA (84 + NEW 14)
smartmeter.0	2020-07-19 20:25:52.148	debug	(26076) MATCH-RESULT MESSAGE: "445a47000282526b7262016503ac4832620263b419007605ae52e00a620062007263070177010b0a01445a47000282526b070100620affff7262016503ac48327577070100603201010172620162006200520004"
smartmeter.0	2020-07-19 20:25:52.145	debug	(26076) ADD NEW DATA (70 + NEW 14)
smartmeter.0	2020-07-19 20:25:52.131	debug	(26076) MATCH-RESULT MESSAGE: "445a47000282526b7262016503ac4832620263b419007605ae52e00a620062007263070177010b0a01445a47000282526b070100620affff7262016503ac4832757707010060" -> null
smartmeter.0	2020-07-19 20:25:52.129	debug	(26076) ADD NEW DATA (56 + NEW 14)
smartmeter.0	2020-07-19 20:25:52.116	debug	(26076) MATCH-RESULT MESSAGE: "445a47000282526b7262016503ac4832620263b419007605ae52e00a620062007263070177010b0a01445a47000282526b070100620affff" -> null
smartmeter.0	2020-07-19 20:25:52.113	debug	(26076) ADD NEW DATA (43 + NEW 13)
smartmeter.0	2020-07-19 20:25:52.100	debug	(26076) MATCH-RESULT MESSAGE: "445a47000282526b7262016503ac4832620263b419007605ae52e00a620062007263070177010b0a01445a" -> null
smartmeter.0	2020-07-19 20:25:52.097	debug	(26076) ADD NEW DATA (29 + NEW 14)
smartmeter.0	2020-07-19 20:25:52.084	debug	(26076) MATCH-RESULT MESSAGE: "445a47000282526b7262016503ac4832620263b419007605ae52e00a62" -> null
smartmeter.0	2020-07-19 20:25:52.081	debug	(26076) ADD NEW DATA (15 + NEW 14)
smartmeter.0	2020-07-19 20:25:52.068	debug	(26076) MATCH-RESULT MESSAGE: "445a47000282526b7262016503ac48" -> null
smartmeter.0	2020-07-19 20:25:52.065	debug	(26076) ADD NEW DATA (0 + NEW 15)
smartmeter.0	2020-07-19 20:25:52.057	debug	(26076) SET MESSAGE TIMEOUT TIMER: 120000
smartmeter.0	2020-07-19 20:25:52.051	debug	(26076) SERIALPORT OPEN`

**Comment by Apollon77** [comment]
Aber das Log zeigt ja einen validen Wert mit 5226.49 W .. oder !? Ich bräuchte ein Log wo es negativ ist bitte

**Comment by Jetiman** [comment]
Unten ist einer mit = -59.96 W

**Comment by Apollon77** [comment]
Ahhh übersehen :-)

**Comment by Apollon77** [comment]
Aber die zeilen sind nicht aus dem Logfile oder? Die zeilen sind wieder abgeschnitten. Sorry, damit leider nicht nutzbar

**Comment by Jetiman** [comment]
Wie meist du das mit abgeschnitten?
Was brauchst du genau und wie komme ich an die Daten?

**Comment by Apollon77** [comment]
Die Zeilen sind nicht Vollständig. Du hast Sie bestimmt aus dem Admin kopiert oder ?

Bitte aus dem Logfile auf der Platte kopieren: /opt/iobroker/log/...

**Comment by Apollon77** [comment]
Ok wenn Sie aus dem logfile kommen dann hat es die beim kopieren über deine Shell abgeschnitten ...

Beispiel: Viele Zeilen haben
smartmeter.0	2020-07-19 20:26:23.683	debug	(26076) MATCH-RESULT MESSAGE: "241b1b1b1b0101010176050a53e00a620062007263010176010102310b0a01445a47000282526b7262016503ac4851620263eb2c0076050b53e00a620062007263070177010b0a01445a47000282526b070100620

... heisst aber das die in wirklichkeit länger sind ... aber das fehlt

**Comment by Jetiman** [comment]
Wie schaut es damit aus?

[log.txt](https://github.com/Apollon77/ioBroker.smartmeter/files/4948743/log.txt)

**Comment by Apollon77** [comment]
Besser :-)

**Comment by Apollon77** [comment]
Schau mal was ich hier gefunden habe ... ich wusste doch das ich das schonmal auseinander genommen habe: https://github.com/Apollon77/smartmeter-obis/issues/75 

Hier ist scheinbar der Zähler Buggy in der Firmware ... kannst Du also bei deinem Energieanbieter reklamieren oder nimmst den adapter und versuchst mal ob bei einem negativen Wert ggf mittels der Umrechnungsformel unter https://github.com/Apollon77/smartmeter-obis/issues/75#issuecomment-581650736 und einem kleinen Javascriptchen fixen kannst.

**Comment by Apollon77** [comment]
PS: Wenn das tut kann ich das noch in die Readme aufnehmen

**Comment by Apollon77** [comment]
In deinem angehängten Log wäre das:

-22.12W --> 633.24W
-32.06W --> 623.3W

passt das?

Dein ganz oben genanntes -94.41W wäre dann nicht ganz dein Wert (aber kann ja leicht anders sein) sondern 560.95W

**Comment by Jetiman** [comment]
Habe noch nicht richtig mit Java gearbeitet. Werde aber versuchen das umzusetzen.

**Comment by Apollon77** [comment]
ANsonsten beschreib das Thema im Forum ind er "Skripen" Sektion, da wirst Du garantiert support bekommen :-)

**Comment by toofii** [comment]
Hey, gibt es hier neue Erkenntnisse? Habe mir auch kürzlich einen IR Kopf besorgt und bekomme bei gleichem Zähler den selben Fehler.

**Comment by Apollon77** [comment]
Naja die Lösung und so um es zu beheben steht oben im Thread sonst wäre es nicht geschlossen. Buggy Firmware ist halt Buggy Firmware
