### ISSUE TITLE
Werte in influxdb

### ISSUE THREAD

**Issue by lschaeferdryden** [Apollon77/ioBroker.smartmeter#149]
Hallo,
der Adapter läuft korrekt in meiner Instanz und die Werte werden auch regelmäßig aktualisiert.
Jetzt wollte ich einzelne Werte in die InfluxDB speichern. Beim Aufruf der Konfig für einen Wert aktiviere ich die InfluxDB Konfig und speichere die Einstellung.
Leider wird die Konfig allerdings nicht gespeichert und die Daten werden nicht an die InfluxDB geliefert. Beim erneuten Aufruf der Konfig ist Influx wieder deaktiviert.

Ist das Problem bereits bekannt?

**Comment by Apollon77** [comment]
Geht bei mir super. Wenn ist das also scheinbar ein Admin issue.
Aber lass mal hier suchen: welcher admin, welcher js-controller?

**Comment by lschaeferdryden** [comment]
Admin: 4.1.7
js-controller: aktuell (Wo kann ich die Version lesen?)

Kann es eventuell an den Doppelpunkten im Namen liegen? Im Log sehe ich aktuell keine Fehlermeldung.

**Comment by Apollon77** [comment]
welche smartmeter version?
Versuch bitte mal admin downgrade auf 4.1.6

**Comment by lschaeferdryden** [comment]
Smartmeter Version: 3.1.3
Downgrade hat leider auch keinen Erfolgt.

**Comment by lschaeferdryden** [comment]
Bei anderen Objekten funktioniert die Sache mit der InfluxDB auch ohne Probleme.
Kann es an den Namen der Objekte liegen?

![Bildschirmfoto 2020-09-02 um 11 41 27](https://user-images.githubusercontent.com/69798913/91965790-4836cf80-ed11-11ea-89fb-dfa281b33f58.png)

**Comment by Apollon77** [comment]
wie gesagt: bei mir tut das alles und daher liegt es nicht an den State IDs.

controller version unter "hosts" im Admin

**Comment by Apollon77** [comment]
wenn du es aktivierst steht irgend ein fehler in der browser konsole?

**Comment by lschaeferdryden** [comment]
In der Konsole kommt eine Warnung. Sonst keine weitere Meldung. Kann es eventuell sein, dass die Objekte nicht korrekt angelegt wurden? 

![Bildschirmfoto 2020-09-02 um 11 45 54](https://user-images.githubusercontent.com/69798913/91966268-e5920380-ed11-11ea-93f8-dd1196b051a5.png)

**Comment by Apollon77** [comment]
and you downgradded admin to 4.1.6.? And completely reloaded in browser??

**Comment by lschaeferdryden** [comment]
Hab den Adapter noch einmal auf die Version 4.1.6 installiert und den Browser Cache geleert. Jetzt funktioniert es wieder. Scheint also ein Problem mit der neuen Admin Version zu sein.

Danke für die schnelle Unterstützung.
