### ISSUE TITLE
Bindings with :

### ISSUE THREAD

**Issue by Parodontitis** [Apollon77/ioBroker.smartmeter#16]
Hi,

smartmeter generiert Datenpunkte wie z.B. **smartmeter.0.1-0:1_8_1_255** 

Das Problem ist, dass man diese Datenpunkte nicht als Bindings in VIS verwenden kann. Wenn ich jetzt im VIS als HTML den Wert mit {smartmeter.0.1-0:1_8_1_255.value} ausgeben will, wird immer ein 0 angezeigt. Meine Vermutung ist, dass es an den Doppelpunkten in DP-Namen liegt. 

Danke

**Comment by Apollon77** [comment]
Dann bitte vis issue anlegen Doppelpunkte sind erlaubte Zeichen in Objekt IDs.
