### ISSUE TITLE
Smartmeter anderen Datenpunkt als Quelle

### ISSUE THREAD

**Issue by lolax80** [Apollon77/ioBroker.smartmeter#160]
Hallo,

erst einmal vielen Danke für den tollen Adapter.
Ich habe Wemos D1 mit einem Lesekopf und Tasmota drauf. Der Iobroker und der Wemos befinden sich an zwei unterschiedlichen Orten.
Ich würde jetzt gerne die Werte welche Tasmota einliest (kWh) an den Smartmeter Adapter schicken wollen.

Könnte man es einen zusätzlichen Punkt bei Datenübertragung geben, wo man einen Objekt/ Datenpunkt aus dem Iobroker auswählen könnte? So könnte man direkt Werte in den Smartmeter einspielen.

Mit freundlichen Grüßen
Alex

**Comment by MMeinhardt1** [comment]
Hi, 
ich hab’s noch nicht getestet aber der SmartMeter Adapter kann Daten über das Netzwerk empfangen. 
Und warum machst du das nicht über MQTT mit dem sonoff Adapter?

**Comment by Apollon77** [comment]
Verstehe ich es korrekt das Du mit der Wemos schon die Daten parst? oder wie? Was ist dann der Sinn es noch zum Adapter zu schicken?

**Comment by lolax80** [comment]
Hallo,

fande die Berechnungen des Adapters toll.
Werde es jetzt aber mit sourceanalytix auswerten.

Danke


Von meinem iPhone gesendet

**Comment by Apollon77** [comment]
Was berechnet der Adapter denn? Der Adapter parst D0 und SML und stellt die Daten als States zur Verfügung. Ich glaube du verwechselst das mit einem anderen Adapter.

**Comment by lolax80** [comment]
Ok, dann habe ich wohl damals was anderes genutzt.

Sorry 

Von meinem iPhone gesendet
