### ISSUE TITLE
Zusätzliche Option "0" als Stop Bit bei den Einstellungen für serielle Geräte

### ISSUE THREAD

**Issue by steini1987** [Apollon77/ioBroker.smartmeter#18]
Hallo,

wie [hier](https://forum.iobroker.net/viewtopic.php?f=23&t=5047&start=1180)  bereits diskutiert, habe ich die Hoffnung, dass ich meinen Zähler mit den Einstellungen 7e0 auslesen kann.

Leider kann im Adapter "0" nicht als Parameter für das Stop-Bit angeben.

Vielen Dank und viele Grüße
Markus

**Comment by Apollon77** [comment]
Sorry. Wert 0 ist Nicht erlaubt für stopbits
