### ISSUE TITLE
IOBroker: Smartmeter switches between yellow and green

### ISSUE THREAD

**Issue by Ingo1977** [Apollon77/ioBroker.smartmeter#189]
Hi,
folgende Situation: 
Der IR Lesekopf (TTL) ist mit meinem ESP8266, auf dem der Serial Server von ESPEasy läuft, verbunden.
Auf meinem Raspberry läuft IOBroker mit dem Smartmeter Adapter.
Die Einstellungen passen soweit und im Log kann ich erkennen, das 10 Werte empfangen werden, allerdings nur bei jedem ca. 5. Versuch, dazwischen ist der Adapter gelb und meldet den Fehler "Error while parsing SML message: Error: Wrong TL-Field".
Nach x Versuchen wechselt er wieder auf grün und empfängt aktualisierte Werte.
Woran liegt das? Was kann ich machen? Als Abfrageintervall habe ich aktuell 10 Sekunden eingestellt. Das funktioniert noch am Besten.
Viele Grüße.

**Comment by Apollon77** [comment]
Ohne details und log kann ich nur raten. Üblicherweise wenn es so ist dann ist der Übertragungsweg gestört (Störstrahlung, also schauen das ggf ein aktiver USB hub genutzt wird, Kabel nicht direkt/zu nah an den Zähler/Stromkabel und so. Weiterhin sitzt oft der Kopf nicht korrekt.

Vor allem wenn die Fehlermelsung und "Stelle" im SML nicht immer gleich ist ist es wahrscheinlich das es so ist. Wenn die Stelle des Fehlers immer idenntisch ist kann es (aber eher unwahrscheinlich) daran liegen das die Firmware des Zählers fehlerhafte Daten sendet
