### ISSUE TITLE
Stromzähler von Holley DTZ541-ZEBA 2018: Error while parsing SML message

### ISSUE THREAD

**Issue by Marti7678** [Apollon77/ioBroker.smartmeter#222]
Hallo,

Ich habe mit dem Smartmeter Adapter Ver 3.2.0 Probleme mit dem SML Protokoll. Die Daten vom ESP scheinen in ioBroker anzukommen, jedoch schreibt der Adapter folgende Fehlermeldungen ins Log.

PS: Ich bin zwar mittlerweile "relativ Fit" mit iobroker, jedoch unerfahren mit Github. Habe die Log mal als Datei angehängt. hoffe das passt soweit und jemand kann mir helfen.

 - Adapter version: 3.2.0
 - JS-Controller version: v12.20.1
 - Node version: v12.20.1
 - Operating system: Pi
[1619954650167-iobroker.2021-05-02.log](https://github.com/Apollon77/ioBroker.smartmeter/files/6435210/1619954650167-iobroker.2021-05-02.log)

**Comment by Apollon77** [comment]
Wenn es ein Zähler-Firmware Issue wäre, wäre der Fehler immer an der gleichen Stelle.
AUch komisch das die erkannten Messages eine andere Länge haben - üblicherweise sind Nachrichten gleich lang.

Von daher liegt es an den Daten die ankommen, da kann ich leider gerade nicht wirklich helfen
