### ISSUE TITLE
Fehlende Auswertung eines Obis Strings

### ISSUE THREAD

**Issue by soeni** [Apollon77/ioBroker.smartmeter#252]
Hi, mein Adapter spuckt mir folgende Fehlermeldung aus:
<html><body>

  | Error while parsing D0 content: ignore complete part Error: Invalid Obis String 1-1:0.5.1.2
-- | --

</body>
</html>

Wenn ich mit einem Terminalprogramm schaue was da drinn steht sieht das so aus:
1-1:1.5.0(00.015*kW)

in der Obis Doku konnt eich das nicht finden, es scheint aber die Momentanleistung mit 3 Stellen zu sein. Gibt es die Möglichkeit solche Obis Werte dennoch im ioBorker zu nutzen, auch wenn sie nicht dem Standard entsprechen?

**Comment by Apollon77** [comment]
In fact same as #152 ... need to find time to think about sich non spec stuff
