### ISSUE TITLE
Mehrfach Log bei zweiter Instanz

### ISSUE THREAD

**Issue by darkiop** [Apollon77/ioBroker.smartmeter#29]
Guten Morgen, ich betreibe aktuell etwas Logfile-Hygiene und dabei ist mir aufgefallen das bei einer zweiten Instanz die Logs für die polls mehrfach geschrieben werden:

![grafik](https://user-images.githubusercontent.com/205119/60068803-906f6080-9710-11e9-87b5-2dcac0d65919.png)

Grüße,
Thorsten

**Comment by Apollon77** [comment]
Was ist da mehrfach? Jede Instanz Logt ihre Daten. Die Zeitpunkte sind hier alle unterschiedlich. Also nichts doppelt.

**Comment by darkiop** [comment]
Hallo Ingo, du hast Recht - mein Fehler, war wohl noch zu früh heut Morgen ;)
