### ISSUE TITLE
3.3.1 and 3.3.2 not working

### ISSUE THREAD

**Issue by arteck** [Apollon77/ioBroker.smartmeter#292]
![grafik](https://user-images.githubusercontent.com/6681528/154893527-fe976fe2-434e-4f16-a293-55f66516827f.png)

settings
![grafik](https://user-images.githubusercontent.com/6681528/154894148-38511ae6-caaf-487b-b402-55f4061811a7.png)

version 3.3.1

i use ser2net for with a raspi

**Comment by TbsJah** [comment]
same for me

**Comment by Ilovegym66** [comment]
same here without ser2net, Raspi Zero with Node 14 and NPM 6.14.16

**Comment by Apollon77** [comment]
fixed in upcoming 3.3.2 https://github.com/Apollon77/ioBroker.smartmeter/actions/runs/1874984749

**Comment by Apollon77** [comment]
Can you please verify that also the "port search" works?

**Comment by TbsJah** [comment]
new version it is not working for me
path is missing

![image](https://user-images.githubusercontent.com/34193151/154917333-5da1c9f9-dbfd-4f15-a4f7-f87a937fa42d.png)

**Comment by Apollon77** [comment]
Ok, 3.3.3 ... next try

**Comment by TbsJah** [comment]
great job - now works like clockwork

**Comment by amg666** [comment]
Master-Slave system, iob 4.0.15 and node.js 14.19.0.
3.3.3 works well, thank you
`<html><body>


host.iobroker | 2022-02-21 11:27:32.665 | info | iobroker exit 0
-- | -- | -- | --
host.iobroker | 2022-02-21 11:27:31.636 | info | iobroker  upload [0] smartmeter.admin  /opt/iobroker/node_modules/iobroker.smartmeter/admin/words.js words.js  application/javascript
host.iobroker | 2022-02-21 11:27:31.628 | info | iobroker upload [1] smartmeter.admin /opt/iobroker/node_modules/iobroker.smartmeter/admin/tooltip.css tooltip.css text/css
host.iobroker | 2022-02-21 11:27:31.619 | info | iobroker  upload [2] smartmeter.admin  /opt/iobroker/node_modules/iobroker.smartmeter/admin/smartmeter.png  smartmeter.png image/png
host.iobroker | 2022-02-21 11:27:31.605 | info | iobroker  upload [3] smartmeter.admin  /opt/iobroker/node_modules/iobroker.smartmeter/admin/smartmeter.jpg  smartmeter.jpg image/jpeg
host.iobroker | 2022-02-21 11:27:31.592 | info | iobroker  upload [4] smartmeter.admin  /opt/iobroker/node_modules/iobroker.smartmeter/admin/questionmark.png  questionmark.png image/png
host.iobroker | 2022-02-21 11:27:31.407 | info | iobroker upload [5] smartmeter.admin /opt/iobroker/node_modules/iobroker.smartmeter/admin/index.html index.html text/html
host.iobroker | 2022-02-21 11:27:31.220 | info | iobroker 168 packages are looking for funding  run `npm fund` for details
host.iobroker | 2022-02-21 11:27:17.796 | info | iobroker + iobroker.smartmeter@3.3.3removed 2 packages and updated 2 packages in 48.752s
host.iobroker | 2022-02-21 11:26:27.623 | info | iobroker NPM version: 6.14.16Installing iobroker.smartmeter@3.3.3... (System call)
host.iobroker | 2022-02-21 11:26:26.987 | info | iobroker Update smartmeter from @3.3.1 to @3.3.3
host.iobroker | 2022-02-21 11:26:25.028 | info | iobroker upgrade smartmeter@3.3.3
host.iobroker | 2022-02-21 11:25:29.332 | info | Updating repository "beta" under "http://download.iobroker.net/sources-dist-latest.json"


</body>
</html>`
