### ISSUE TITLE
Adapter stays "red" after update to 3.3.1

### ISSUE THREAD

**Issue by amg666** [Apollon77/ioBroker.smartmeter#293]
master-slave system with smartmeter adapter on the slave (raspi3b), both systems in beta repository (node.js 14.19.0 and iob 4.0.15):

`<html><body>

host.iostrom | 2022-02-21 09:40:26.347 | info | Restart adapter system.adapter.smartmeter.0 because enabled
-- | -- | -- | --
host.iostrom | 2022-02-21 09:40:26.345 | error | instance system.adapter.smartmeter.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.iostrom | 2022-02-21 09:40:26.344 | error | Caught by controller[1]:     at /opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.js:9128:26
host.iostrom | 2022-02-21 09:40:26.343 | error | Caught by controller[1]:     at Adapter.emit (domain.js:475:12)
host.iostrom | 2022-02-21 09:40:26.341 | error | Caught by controller[1]:     at Adapter.emit (events.js:400:28)
host.iostrom | 2022-02-21 09:40:26.340 | error | Caught by controller[1]:     at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.smartmeter/smartmeter.js:169:13)
host.iostrom | 2022-02-21 09:40:26.339 | error | Caught by controller[1]:     at main (/opt/iobroker/node_modules/iobroker.smartmeter/smartmeter.js:365:34)
host.iostrom | 2022-02-21 09:40:26.336 | error | Caught by controller[1]:     at Object.init (/opt/iobroker/node_modules/smartmeter-obis/index.js:72:17)
host.iostrom | 2022-02-21 09:40:26.335 | error | Caught  by controller[1]:     at SerialResponseTransport.init  (/opt/iobroker/node_modules/smartmeter-obis/lib/transports/SerialResponseTransport.js:45:27)
host.iostrom | 2022-02-21 09:40:26.334 | error | Caught by controller[1]:     at new SerialPort (/opt/iobroker/node_modules/serialport/dist/serialport.js:13:9)
host.iostrom | 2022-02-21 09:40:26.333 | error | Caught by controller[1]:     at new SerialPortStream (/opt/iobroker/node_modules/@serialport/stream/dist/index.js:50:19)
host.iostrom | 2022-02-21 09:40:26.332 | error | Caught by controller[1]: TypeError: "path" is not defined: undefined
host.iostrom | 2022-02-21 09:40:26.330 | error | Caught  by controller[0]: This error originated either by throwing inside of an  async function without a catch block, or by rejecting a promise which  was not handled with .catch(). The promise rejected with the reason:
smartmeter.0 | 2022-02-21 09:40:25.351 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
smartmeter.0 | 2022-02-21 09:40:25.345 | info | terminating

</body>
</html>

after downgrade to 3.2.1 everything works fine.

**Comment by Apollon77** [comment]
3.3.3 on the way that hopefully fixes it
