### ISSUE TITLE
Sync data fetch timestamp with other instance of this adapter

### ISSUE THREAD

**Issue by Loenne83** [Apollon77/ioBroker.smartmeter#307]
**Problem:**
When using two instances of this adapter, they might be not simultaneously fetch data, even if this would be interesting, because they both get power data. When calculating differences of these values, the time difference leads to inaccurate data.

**Possible solution:**
Get an option in the instance setting, where the instance to be synced to can be named (i.e. "smartmeter.1"). Alternatively, defining a cron timeplan for each instance would do the job either, I suppose.

**Comment by Apollon77** [comment]
Syncing between instances will not be that easiely possible, honestly ... then I more like the idea in #308 because with a "refresh" state that you can trigger you can achieve exactly this behaviour here by just setting both states (one per instance) at the same time Thats why I close this one

**Comment by Loenne83** [comment]
since I'm not deep into the adapter structure it was just an idea. I agree with your opinion, but what about the cron option? On the other hand, this would indirectly also be possible with the solution in #308, correct?

**Comment by Apollon77** [comment]
yes, also possible - controlled by a script of you
