### ISSUE TITLE
Fehler mit 2 smartmeter Instanzen 

### ISSUE THREAD

**Issue by MatthiasEscher** [Apollon77/ioBroker.smartmeter#315]
Hallo zusammen, 

ich habe ein Problem, welches ich mir nicht erklären kann: 

Ich habe 2 USB Leseköpfe an einem Raspberry PI und lese diese mit dem iobroker aus. 
Das funktioniert eigentlich auch wunderbar. Nach ca. 18-24 Stunden Betrieb steigt jedoch eine der Instanzen aus (Das ist zufällig. Ich dachte erst, dass es immer die Gleiche ist aber nun ist auch die andere mal abgestürzt, wobei die andere sauber weiter läuft). Die Instanz geht dann auf Gelb und es wird "No or too long answer from Serial Device after last request." angezeigt. 

Der Lesekopf hat eine LED und empfängt auch noch Daten. Wenn ich dann versuche, mit minicom die Schnittstelle, die nicht funktioniert zu öffnen erhalte ich die Meldung: "minicom: Fehler beim Öffnen der Datei »/dev/ttyUSB0«: Nicht genügend Hauptspeicher verfügbar". Das bekomme ich immer für die Schnittstelle, die im iobroker dann auch nicht funktioniert. 

Auch der Zugriff über NodeRed zeigt den gleichen Fehler wie bei minicom. Ich kann mir das aber beim besten Willen nicht erklären. Der Arbeitsspeicher und die Speicherkarte sind überhaupt nicht ausgelastet. 

Wenn ich den USB Lesekopf einmal abziehe, dann geht es meistens knapp einen Tag wieder. Auch ein Neustart vom PI löst das Probleme einige Stunden. 

Falls sich das jemand erklären kann oder ob es noch an dem Zugriff über den Adapter liegt, lasst es mich gerne wissen.

**Comment by Apollon77** [comment]
Das klingt eher wie ein Forum  Support Thema und weniger das Du da im GitHub viel hilfe bekommen kannst. Ich würde anfangen mit Kernel aktualisieren, schauen ob in "dmesg" irgendwas geloggt wird.

Ist in meinen Augen aber nichts wo der Adapter etwas für kann
