### ISSUE TITLE
[Feature Request]  EEBus Support

### ISSUE THREAD

**Issue by stilicrafter** [Apollon77/ioBroker.smartmeter#323]
**Is your feature request related to a problem? Please describe.**
I am frustrated that EEBus is not supported

**Describe the solution you'd like**
Integrate EEBus 

**Describe alternatives you've considered**
Seartched for standalone EEBus, but didnt find any plugin

**Additional context**
It looks like EEBus and EBus are different systems, but EEBus should be similar to ModBus TCP

**Comment by Apollon77** [comment]
is eebus data OBIS based?

**Comment by Apollon77** [comment]
I checked the specs and I think an own adapter makes more sense, also because no OBIS is used according to the specs

**Comment by stilicrafter** [comment]
No Problem.
I opened the request to add it as a new Adapter.

Thank you
