### ISSUE TITLE
Support for Sharks 775 (Diehl)

### ISSUE THREAD

**Issue by flispy** [Apollon77/ioBroker.smartmeter#338]
Hi,

I would like to receive data from WMZ Sharks 775 over ZVEI. I found documentation for this counter via https://docplayer.org/46052594-Sharky-775-kommunikationsbeschreibung.html and setup the adapter with these mentioned values. 
<img width="412" alt="Bildschirmfoto 2022-10-21 um 15 47 33" src="https://user-images.githubusercontent.com/15381702/197211287-a534caf1-efcc-49dc-b19d-41ae85cdda2f.png">
But in any case I am not able to receive data. In general it works for another power-supply-counter with standard settings.
These are my DEBUG outputs from protocol.
<img width="1236" alt="Bildschirmfoto 2022-10-21 um 15 49 32" src="https://user-images.githubusercontent.com/15381702/197211617-47ff5451-c1f0-4200-a391-52880318903b.png">
Do you have some idea how we can get it working?

**Comment by Apollon77** [comment]
Hm ... the spec states that it is mbus protocol and not  D0 or SML ... so the mbus Adaoter would be more your friend. ZVEI is a protocol type I hear for the first time but it seems to be "MBus over optiocal" which is also not supported by Mbus adapter

So effectively you could create a feature request for mbus adapter to implement that but this is very special. Or you switch to 2-wire MBus standard and use MBus adapter with an MBus master devices.

So or so , nothing for smartmeter adapter
