### ISSUE TITLE
Log Spam: Received 7 values, 3 updated

### ISSUE THREAD

**Issue by fah** [Apollon77/ioBroker.smartmeter#35]
Mein Log wird mit 6 Zeilen / Minute gefüllt.

"Received 7 values, 3 updated"

Die Nachricht ist im stabilen Betrieb nicht mehr notwendig.

Ich schlage vor, dass eine Option hinzugefügt wird, die das Logging nach Bedarf filtert.
Z.B. debug / info / warning

**Comment by Apollon77** [comment]
Bitte die Instanz auf Loglevel "warn" setzen. Admin - Instanzen - Expertenmodus - Spalte Logstufe

**Comment by fah** [comment]
Rasant! :-) Danke! Wusste nicht das diese Spalte existiert.

**Comment by Apollon77** [comment]
;-) manchmal wenn ich grad am Mails aufräumen bin gehts fix ;-)
