### ISSUE TITLE
Sync to instances of smartmeter adapter

### ISSUE THREAD

**Issue by danickel** [Apollon77/ioBroker.smartmeter#359]
I have to meters in series. In between there is the heating pump. 
To get the current consumption of the heating pump I have to substract consumption of meter2 from meter1.
This I want to do in iobroker, but the problem is that the two instances of the smartmeter adapter are reading the values asynchron.

My feature request is, to have an option to synchronize instances that they are reading the meters at the same time or to have one adapter where I can add more than one meter and that they are then reading at the same time.

Regards,
danickel

**Comment by Apollon77** [comment]
duplicate https://github.com/Apollon77/ioBroker.smartmeter/issues/326
