### ISSUE TITLE
Engelmann SensoStar U - Adapter Einstellungen

### ISSUE THREAD

**Issue by SuperDa75** [Apollon77/ioBroker.smartmeter#361]
Hallo zusammen,

ich komme bei den Adapter Einstellungen im ioBroker nicht weiter, benötige bitte Unterstützung.

Besitze einen **Engelmann SensoStar U** und einen **IR-Lese/Schreibkopf**, der im ioBroker als **CP2102** erkannt wird.

Nach langer Recherche konnte ich folgende Parameter für die Kommunikation mit dem WMZ herausfinden:

1. **aufwecken**: Baud **2.400** / Data-Bits **8** / Stop-Bits **1** / Parität **N** > **53x 55555555555555555555** senden
2. **Wartezeit**: **350ms**
3. **Protokollwechsel**: Baud 2.400 / Data-Bits 8 / Stop-Bits 1 / Parität **E** > **105BFE5916** senden

Die offensichtlichen Daten habe ich im Smartmeter-Adapter eingetragen, komme allerdings bei den D0 Werten nicht weiter. 
Wie soll ich die o.g. Werte eintragen?

Danke Euch!
Daniel

**Comment by Apollon77** [comment]
Bitte am besten im Forum posten, da sind mehr user.

generell gilt: zuerst GAR NICHTS ändern ... dann so wenig wie möglich ändern, meistens hat mal falsche annahmen!

Generell ist alles was ich hier lese komplett kein Standard ... das man "5" senden muss ...der Adapter sendet 0 weil das bei allem anderen tut. Da kannst du sagen wie oft.

Am besten Forum post, PDF oder was auch immer du an infos hast dazu und mich mentionen
