### ISSUE TITLE
Instanz geht nicht mehr auf Grün

### ISSUE THREAD

**Issue by Hilti23** [Apollon77/ioBroker.smartmeter#377]
Hallo zusammen,

ich habe das Problem, dass meine Smartmeter Instanz nicht mehr auf Grün geht.
Dieser ist per UART an einem Raspi 4 angeschlossen und hat schon mehrere Montate problemlos funktioniert.
Ich weiß leider nicht mehr was ich machen soll und hoffe dass mir jemand Helfen kann.

Hier ein kleiner Ausschnitt der Log-Einträge:

`<html>
<body>

smartmeter.0 | 2023-10-11 15:07:38.740 | info | terminating
-- | -- | -- | --
smartmeter.0 | 2023-10-11 15:07:38.251 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
smartmeter.0 | 2023-10-11 15:07:38.249 | debug | Plugin sentry destroyed
smartmeter.0 | 2023-10-11 15:07:38.246 | info | terminating
smartmeter.0 | 2023-10-11 15:07:38.242 | debug | SERIALPORT CLOSE
smartmeter.0 | 2023-10-11 15:07:38.232 | info | Got terminate signal TERMINATE_YOURSELF
smartmeter.0 | 2023-10-11 15:07:38.069 | debug | MATCH-RESULT MESSAGE: "773180a67564ae78fc627d8d750265a2c1ff7bb4443d04aec0dc20d502652006a6c4ff00e60080d5b800800088882495c10000132188761601f020001008f616bb03000088802a44984085008098000100008c20a2890028241120260400220080049f4402a00094dc7705ff773180442d80aa18dc407d08740265a2c1e723b0e42524aec0fc203502650082a2c16600a60040d598008000048c2095c00000172588561601f02204908876163b8e00040c802a44984000c0009800010400cc00a68d002424112022000022008003e4fd23a00480e23700ff773180a43520aa38fc407f88d50645a2c1efbfb4443d2406c0dc21d592650082a2c1ef22e60080379800804400882415c0200056756765494504f420041088f612bb0c000088806e44984000400098004000008822e6cc006c24190026000022004004443523a0cc00047717f9770380243d20ee38dc407f8d774665a6c4e77734442420aae2dc01d406650082a2c1e700e60000d498008000008800aac1000013212076560174220410887616bfe3000008802a11980000000098000000008c00a68d002c24ed0022600022004081e42d006e107f0c7745fe7731c04424205218dc627d8d750275e6c1ee0fb0442c24aa60dc207706750056a6c4ef22a60080239800800080882095c10000172548f61201702000b888f6123e8d200088802a14980005000098000000008800e6cc0028241922262000220080b14434202a30bf8c7700ff773180443d24aa18dc407d88f50655a2c1f79bb0443564aec0dc357502650086a2c4f700a20080d59800800080882095c10000132488761204f4000490085656bf82000088802e449800900000b8000100488c00a60d006c24e50026000022001408447d242e102b247785e7771180447564ae18dc407f883606650a64f680c5e42c20aec0dc207502652286a2c17700a20400f59c00800000882495c12000172560f616017022041008f612bb8f00008884224498000000009c000100008c00a60d002824e500220000220080b44475646e10738c2380f8773180442d24ae18dc407f88350665a223f723b0e67564ee60dc217402650086a2c1f726220000d59800800004880095c0000013219c561201f42200108876123fe8980004000824040002cc00f82015880480d8000e20002824d900220000220114c3443c20026680713785ff773180443524ae18dc20318d230265a6c47feff4447d24aec0dc20d5024500d6a6617f00260480d49c00800000882495610000172588f616a37020001008f612bfc60044cc802e449840000088980000c0008820a2890028261920220004220080024445242e10bf283780f9771180444d20aa187e403188750245a2c1c7f7b444452002c0dc00d402652006a621c700260080d59c00800000882095c120001321207616e7e098448510607612bb05000088802e449844050088f8000004008c00a6cc006c24e500662200220080089fc506240c00047717b4893180e655642e18dc407388750265e6c44f6bb4445d20aac0dc207506750086e6c1ce20a60080749800804000882495630000132488f63601f426041088f612bb980044000824040006000cf826018cc08000a60d002824d90066600022011482449503a4886c157717fa971180a45d24aa18dc607388d50645a2c1c72360444524aec0dc00d406450086a2c1c700260080d59800800004882095c020001371e761550501f0220010887612bb8320048c802e44980080000098000100008800a28d002c2411202200008a0000c0445d646e1063dc9700f1771380264524aa18dc40718d77026502c4cfeb34444c20aa62fe01d402650086a2c1ce00a20080d59800800000886415e12000172188f61201f420041088f612bb8f0000cc802a1598000500009c000000008800e6cc00282419002200002200001d9f440902630555771799770180445423a08088407100d50265a6c1d637b4e45420ae62dc01f506750082a6c4d700a60040d59c00c00080e02095c1220017219c76d5fc01f42000108876d57c0d98c0040008240420064000f800010c008000a68d002024112626000022008007445c202a10378c7700fd7731c04445240218dc627388f50265a2c1df5774444d20aec0dc20f5026522d6a6c15700a20080d598008000008820d5c12200162588f6d5fc01f420001088f6d5786d0820048880224498000000009c000104008c00a60d04282425262200000a0000b4a445242e102b887705fc771180444d24aa18dc4073887502650661d737b4445500aac0dc217546450082a662d720a6048475f8008000008820d5c1000013218876b3fc01f02204d08876f57c6d81000088802a44984400000098000004008800e68c00202419002200040a008003e45d242e103b887785f37731804455240218dc627588d4c6155d88f661079bc41b4667dc217402450082e663df00a60080d59800800080882495c10000162188f6f5fca2702204108856d5784db100048c8026449800900404b80000004c882022890028771100260000220028814445042e1063087705fd773180444c20aa18dc40750dd40265a2c1c7b7b0e44524aec0dc20d5067500d6a2c1c700a24480d59800800000a064d5c100001321087649f801f4988080b8887649784d8a00048c802e4498000000009800010000cc22a28d002c241122660000220000c1444d242a10f7887785fb771180447420aa18fe40358d760265a2c1cf2bf4445d04aec0dc20d50265008626e1cf00260080d5f8008000c87344a0110000172588f649f8a1f02200b888f649784d6000040c842a44980005000098440100408c00a609002c24d10066000022008007445464566680013717fb773180445d24aac08866778d770665a2c1c7e3b4446504aec0dc35d50205208222c1c600a60080d5b800800088882095c00000132108764974a1f0200010207649784d0700048cc02e44984005009c7f00000c0084002289002824190026000022010005446d202e10f3887745eb77038044e50623678bdc407508770265a663cf37b0446d24aec0fe002302652082a6c14720a60084d59c00800000882095c10000132560f649f801f42000109cf649744d880000cc806e44b80005cc00f8000004008800a2cc002c241100220440220080c2e675202e6680847717e1373180e47c20ae18dc60758dd4026522c1d7ebb0447520aac0dc20d5024500d6a661d700a20080d59800800000e4209563200016218876c9f801f0220410887649784ce20044cc802e44d80000440098000000008800e6cc002c2419262204006227a8c1a47c242e70a7407700ff" -> null
smartmeter.0 | 2023-10-11 15:07:38.068 | debug | ADD NEW DATA (2397 + NEW 1)
smartmeter.0 | 2023-10-11 15:07:38.064 | debug | MATCH-RESULT MESSAGE: "773180a67564ae78fc627d8d750265a2c1ff7bb4443d04aec0dc20d502652006a6c4ff00e60080d5b800800088882495c10000132188761601f020001008f616bb03000088802a44984085008098000100008c20a2890028241120260400220080049f4402a00094dc7705ff773180442d80aa18dc407d08740265a2c1e723b0e42524aec0fc203502650082a2c16600a60040d598008000048c2095c00000172588561601f02204908876163b8e00040c802a44984000c0009800010400cc00a68d002424112022000022008003e4fd23a00480e23700ff773180a43520aa38fc407f88d50645a2c1efbfb4443d2406c0dc21d592650082a2c1ef22e60080379800804400882415c0200056756765494504f420041088f612bb0c000088806e44984000400098004000008822e6cc006c24190026000022004004443523a0cc00047717f9770380243d20ee38dc407f8d774665a6c4e77734442420aae2dc01d406650082a2c1e700e60000d498008000008800aac1000013212076560174220410887616bfe3000008802a11980000000098000000008c00a68d002c24ed0022600022004081e42d006e107f0c7745fe7731c04424205218dc627d8d750275e6c1ee0fb0442c24aa60dc207706750056a6c4ef22a60080239800800080882095c10000172548f61201702000b888f6123e8d200088802a14980005000098000000008800e6cc0028241922262000220080b14434202a30bf8c7700ff773180443d24aa18dc407d88f50655a2c1f79bb0443564aec0dc357502650086a2c4f700a20080d59800800080882095c10000132488761204f4000490085656bf82000088802e449800900000b8000100488c00a60d006c24e50026000022001408447d242e102b247785e7771180447564ae18dc407f883606650a64f680c5e42c20aec0dc207502652286a2c17700a20400f59c00800000882495c12000172560f616017022041008f612bb8f00008884224498000000009c000100008c00a60d002824e500220000220080b44475646e10738c2380f8773180442d24ae18dc407f88350665a223f723b0e67564ee60dc217402650086a2c1f726220000d59800800004880095c0000013219c561201f42200108876123fe8980004000824040002cc00f82015880480d8000e20002824d900220000220114c3443c20026680713785ff773180443524ae18dc20318d230265a6c47feff4447d24aec0dc20d5024500d6a6617f00260480d49c00800000882495610000172588f616a37020001008f612bfc60044cc802e449840000088980000c0008820a2890028261920220004220080024445242e10bf283780f9771180444d20aa187e403188750245a2c1c7f7b444452002c0dc00d402652006a621c700260080d59c00800000882095c120001321207616e7e098448510607612bb05000088802e449844050088f8000004008c00a6cc006c24e500662200220080089fc506240c00047717b4893180e655642e18dc407388750265e6c44f6bb4445d20aac0dc207506750086e6c1ce20a60080749800804000882495630000132488f63601f426041088f612bb980044000824040006000cf826018cc08000a60d002824d90066600022011482449503a4886c157717fa971180a45d24aa18dc607388d50645a2c1c72360444524aec0dc00d406450086a2c1c700260080d59800800004882095c020001371e761550501f0220010887612bb8320048c802e44980080000098000100008800a28d002c2411202200008a0000c0445d646e1063dc9700f1771380264524aa18dc40718d77026502c4cfeb34444c20aa62fe01d402650086a2c1ce00a20080d59800800000886415e12000172188f61201f420041088f612bb8f0000cc802a1598000500009c000000008800e6cc00282419002200002200001d9f440902630555771799770180445423a08088407100d50265a6c1d637b4e45420ae62dc01f506750082a6c4d700a60040d59c00c00080e02095c1220017219c76d5fc01f42000108876d57c0d98c0040008240420064000f800010c008000a68d002024112626000022008007445c202a10378c7700fd7731c04445240218dc627388f50265a2c1df5774444d20aec0dc20f5026522d6a6c15700a20080d598008000008820d5c12200162588f6d5fc01f420001088f6d5786d0820048880224498000000009c000104008c00a60d04282425262200000a0000b4a445242e102b887705fc771180444d24aa18dc4073887502650661d737b4445500aac0dc217546450082a662d720a6048475f8008000008820d5c1000013218876b3fc01f02204d08876f57c6d81000088802a44984400000098000004008800e68c00202419002200040a008003e45d242e103b887785f37731804455240218dc627588d4c6155d88f661079bc41b4667dc217402450082e663df00a60080d59800800080882495c10000162188f6f5fca2702204108856d5784db100048c8026449800900404b80000004c882022890028771100260000220028814445042e1063087705fd773180444c20aa18dc40750dd40265a2c1c7b7b0e44524aec0dc20d5067500d6a2c1c700a24480d59800800000a064d5c100001321087649f801f4988080b8887649784d8a00048c802e4498000000009800010000cc22a28d002c241122660000220000c1444d242a10f7887785fb771180447420aa18fe40358d760265a2c1cf2bf4445d04aec0dc20d50265008626e1cf00260080d5f8008000c87344a0110000172588f649f8a1f02200b888f649784d6000040c842a44980005000098440100408c00a609002c24d10066000022008007445464566680013717fb773180445d24aac08866778d770665a2c1c7e3b4446504aec0dc35d50205208222c1c600a60080d5b800800088882095c00000132108764974a1f0200010207649784d0700048cc02e44984005009c7f00000c0084002289002824190026000022010005446d202e10f3887745eb77038044e50623678bdc407508770265a663cf37b0446d24aec0fe002302652082a6c14720a60084d59c00800000882095c10000132560f649f801f42000109cf649744d880000cc806e44b80005cc00f8000004008800a2cc002c241100220440220080c2e675202e6680847717e1373180e47c20ae18dc60758dd4026522c1d7ebb0447520aac0dc20d5024500d6a661d700a20080d59800800000e4209563200016218876c9f801f0220410887649784ce20044cc802e44d80000440098000000008800e6cc002c2419262204006227a8c1a47c242e70a7407700" -> null
smartmeter.0 | 2023-10-11 15:07:38.064 | debug | ADD NEW DATA (2396 + NEW 1)
smartmeter.0 | 2023-10-11 15:07:38.060 | debug | MATCH-RESULT MESSAGE: "773180a67564ae78fc627d8d750265a2c1ff7bb4443d04aec0dc20d502652006a6c4ff00e60080d5b800800088882495c10000132188761601f020001008f616bb03000088802a44984085008098000100008c20a2890028241120260400220080049f4402a00094dc7705ff773180442d80aa18dc407d08740265a2c1e723b0e42524aec0fc203502650082a2c16600a60040d598008000048c2095c00000172588561601f02204908876163b8e00040c802a44984000c0009800010400cc00a68d002424112022000022008003e4fd23a00480e23700ff773180a43520aa38fc407f88d50645a2c1efbfb4443d2406c0dc21d592650082a2c1ef22e60080379800804400882415c0200056756765494504f420041088f612bb0c000088806e44984000400098004000008822e6cc006c24190026000022004004443523a0cc00047717f9770380243d20ee38dc407f8d774665a6c4e77734442420aae2dc01d406650082a2c1e700e60000d498008000008800aac1000013212076560174220410887616bfe3000008802a11980000000098000000008c00a68d002c24ed0022600022004081e42d006e107f0c7745fe7731c04424205218dc627d8d750275e6c1ee0fb0442c24aa60dc207706750056a6c4ef22a60080239800800080882095c10000172548f61201702000b888f6123e8d200088802a14980005000098000000008800e6cc0028241922262000220080b14434202a30bf8c7700ff773180443d24aa18dc407d88f50655a2c1f79bb0443564aec0dc357502650086a2c4f700a20080d59800800080882095c10000132488761204f4000490085656bf82000088802e449800900000b8000100488c00a60d006c24e50026000022001408447d242e102b247785e7771180447564ae18dc407f883606650a64f680c5e42c20aec0dc207502652286a2c17700a20400f59c00800000882495c12000172560f616017022041008f612bb8f00008884224498000000009c000100008c00a60d002824e500220000220080b44475646e10738c2380f8773180442d24ae18dc407f88350665a223f723b0e67564ee60dc217402650086a2c1f726220000d59800800004880095c0000013219c561201f42200108876123fe8980004000824040002cc00f82015880480d8000e20002824d900220000220114c3443c20026680713785ff773180443524ae18dc20318d230265a6c47feff4447d24aec0dc20d5024500d6a6617f00260480d49c00800000882495610000172588f616a37020001008f612bfc60044cc802e449840000088980000c0008820a2890028261920220004220080024445242e10bf283780f9771180444d20aa187e403188750245a2c1c7f7b444452002c0dc00d402652006a621c700260080d59c00800000882095c120001321207616e7e098448510607612bb05000088802e449844050088f8000004008c00a6cc006c24e500662200220080089fc506240c00047717b4893180e655642e18dc407388750265e6c44f6bb4445d20aac0dc207506750086e6c1ce20a60080749800804000882495630000132488f63601f426041088f612bb980044000824040006000cf826018cc08000a60d002824d90066600022011482449503a4886c157717fa971180a45d24aa18dc607388d50645a2c1c72360444524aec0dc00d406450086a2c1c700260080d59800800004882095c020001371e761550501f0220010887612bb8320048c802e44980080000098000100008800a28d002c2411202200008a0000c0445d646e1063dc9700f1771380264524aa18dc40718d77026502c4cfeb34444c20aa62fe01d402650086a2c1ce00a20080d59800800000886415e12000172188f61201f420041088f612bb8f0000cc802a1598000500009c000000008800e6cc00282419002200002200001d9f440902630555771799770180445423a08088407100d50265a6c1d637b4e45420ae62dc01f506750082a6c4d700a60040d59c00c00080e02095c1220017219c76d5fc01f42000108876d57c0d98c0040008240420064000f800010c008000a68d002024112626000022008007445c202a10378c7700fd7731c04445240218dc627388f50265a2c1df5774444d20aec0dc20f5026522d6a6c15700a20080d598008000008820d5c12200162588f6d5fc01f420001088f6d5786d0820048880224498000000009c000104008c00a60d04282425262200000a0000b4a445242e102b887705fc771180444d24aa18dc4073887502650661d737b4445500aac0dc217546450082a662d720a6048475f8008000008820d5c1000013218876b3fc01f02204d08876f57c6d81000088802a44984400000098000004008800e68c00202419002200040a008003e45d242e103b887785f37731804455240218dc627588d4c6155d88f661079bc41b4667dc217402450082e663df00a60080d59800800080882495c10000162188f6f5fca2702204108856d5784db100048c8026449800900404b80000004c882022890028771100260000220028814445042e1063087705fd773180444c20aa18dc40750dd40265a2c1c7b7b0e44524aec0dc20d5067500d6a2c1c700a24480d59800800000a064d5c100001321087649f801f4988080b8887649784d8a00048c802e4498000000009800010000cc22a28d002c241122660000220000c1444d242a10f7887785fb771180447420aa18fe40358d760265a2c1cf2bf4445d04aec0dc20d50265008626e1cf00260080d5f8008000c87344a0110000172588f649f8a1f02200b888f649784d6000040c842a44980005000098440100408c00a609002c24d10066000022008007445464566680013717fb773180445d24aac08866778d770665a2c1c7e3b4446504aec0dc35d50205208222c1c600a60080d5b800800088882095c00000132108764974a1f0200010207649784d0700048cc02e44984005009c7f00000c0084002289002824190026000022010005446d202e10f3887745eb77038044e50623678bdc407508770265a663cf37b0446d24aec0fe002302652082a6c14720a60084d59c00800000882095c10000132560f649f801f42000109cf649744d880000cc806e44b80005cc00f8000004008800a2cc002c241100220440220080c2e675202e6680847717e1373180e47c20ae18dc60758dd4026522c1d7ebb0447520aac0dc20d5024500d6a661d700a20080d59800800000e4209563200016218876c9f801f0220410887649784ce20044cc802e44d80000440098000000008800e6cc002c2419262204006227a8c1a47c242e70a74077" -> null
smartmeter.0 | 2023-10-11 15:07:38.060 | debug | ADD NEW DATA (2394 + NEW 2)
smartmeter.0 | 2023-10-11 15:07:38.056 | debug | MATCH-RESULT MESSAGE: "773180a67564ae78fc627d8d750265a2c1ff7bb4443d04aec0dc20d502652006a6c4ff00e60080d5b800800088882495c10000132188761601f020001008f616bb03000088802a44984085008098000100008c20a2890028241120260400220080049f4402a00094dc7705ff773180442d80aa18dc407d08740265a2c1e723b0e42524aec0fc203502650082a2c16600a60040d598008000048c2095c00000172588561601f02204908876163b8e00040c802a44984000c0009800010400cc00a68d002424112022000022008003e4fd23a00480e23700ff773180a43520aa38fc407f88d50645a2c1efbfb4443d2406c0dc21d592650082a2c1ef22e60080379800804400882415c0200056756765494504f420041088f612bb0c000088806e44984000400098004000008822e6cc006c24190026000022004004443523a0cc00047717f9770380243d20ee38dc407f8d774665a6c4e77734442420aae2dc01d406650082a2c1e700e60000d498008000008800aac1000013212076560174220410887616bfe3000008802a11980000000098000000008c00a68d002c24ed0022600022004081e42d006e107f0c7745fe7731c04424205218dc627d8d750275e6c1ee0fb0442c24aa60dc207706750056a6c4ef22a60080239800800080882095c10000172548f61201702000b888f6123e8d200088802a14980005000098000000008800e6cc0028241922262000220080b14434202a30bf8c7700ff773180443d24aa18dc407d88f50655a2c1f79bb0443564aec0dc357502650086a2c4f700a20080d59800800080882095c10000132488761204f4000490085656bf82000088802e449800900000b8000100488c00a60d006c24e50026000022001408447d242e102b247785e7771180447564ae18dc407f883606650a64f680c5e42c20aec0dc207502652286a2c17700a20400f59c00800000882495c12000172560f616017022041008f612bb8f00008884224498000000009c000100008c00a60d002824e500220000220080b44475646e10738c2380f8773180442d24ae18dc407f88350665a223f723b0e67564ee60dc217402650086a2c1f726220000d59800800004880095c0000013219c561201f42200108876123fe8980004000824040002cc00f82015880480d8000e20002824d900220000220114c3443c20026680713785ff773180443524ae18dc20318d230265a6c47feff4447d24aec0dc20d5024500d6a6617f00260480d49c00800000882495610000172588f616a37020001008f612bfc60044cc802e449840000088980000c0008820a2890028261920220004220080024445242e10bf283780f9771180444d20aa187e403188750245a2c1c7f7b444452002c0dc00d402652006a621c700260080d59c00800000882095c120001321207616e7e098448510607612bb05000088802e449844050088f8000004008c00a6cc006c24e500662200220080089fc506240c00047717b4893180e655642e18dc407388750265e6c44f6bb4445d20aac0dc207506750086e6c1ce20a60080749800804000882495630000132488f63601f426041088f612bb980044000824040006000cf826018cc08000a60d002824d90066600022011482449503a4886c157717fa971180a45d24aa18dc607388d50645a2c1c72360444524aec0dc00d406450086a2c1c700260080d59800800004882095c020001371e761550501f0220010887612bb8320048c802e44980080000098000100008800a28d002c2411202200008a0000c0445d646e1063dc9700f1771380264524aa18dc40718d77026502c4cfeb34444c20aa62fe01d402650086a2c1ce00a20080d59800800000886415e12000172188f61201f420041088f612bb8f0000cc802a1598000500009c000000008800e6cc00282419002200002200001d9f440902630555771799770180445423a08088407100d50265a6c1d637b4e45420ae62dc01f506750082a6c4d700a60040d59c00c00080e02095c1220017219c76d5fc01f42000108876d57c0d98c0040008240420064000f800010c008000a68d002024112626000022008007445c202a10378c7700fd7731c04445240218dc627388f50265a2c1df5774444d20aec0dc20f5026522d6a6c15700a20080d598008000008820d5c12200162588f6d5fc01f420001088f6d5786d0820048880224498000000009c000104008c00a60d04282425262200000a0000b4a445242e102b887705fc771180444d24aa18dc4073887502650661d737b4445500aac0dc217546450082a662d720a6048475f8008000008820d5c1000013218876b3fc01f02204d08876f57c6d81000088802a44984400000098000004008800e68c00202419002200040a008003e45d242e103b887785f37731804455240218dc627588d4c6155d88f661079bc41b4667dc217402450082e663df00a60080d59800800080882495c10000162188f6f5fca2702204108856d5784db100048c8026449800900404b80000004c882022890028771100260000220028814445042e1063087705fd773180444c20aa18dc40750dd40265a2c1c7b7b0e44524aec0dc20d5067500d6a2c1c700a24480d59800800000a064d5c100001321087649f801f4988080b8887649784d8a00048c802e4498000000009800010000cc22a28d002c241122660000220000c1444d242a10f7887785fb771180447420aa18fe40358d760265a2c1cf2bf4445d04aec0dc20d50265008626e1cf00260080d5f8008000c87344a0110000172588f649f8a1f02200b888f649784d6000040c842a44980005000098440100408c00a609002c24d10066000022008007445464566680013717fb773180445d24aac08866778d770665a2c1c7e3b4446504aec0dc35d50205208222c1c600a60080d5b800800088882095c00000132108764974a1f0200010207649784d0700048cc02e44984005009c7f00000c0084002289002824190026000022010005446d202e10f3887745eb77038044e50623678bdc407508770265a663cf37b0446d24aec0fe002302652082a6c14720a60084d59c00800000882095c10000132560f649f801f42000109cf649744d880000cc806e44b80005cc00f8000004008800a2cc002c241100220440220080c2e675202e6680847717e1373180e47c20ae18dc60758dd4026522c1d7ebb0447520aac0dc20d5024500d6a661d700a20080d59800800000e4209563200016218876c9f801f0220410887649784ce20044cc802e44d80000440098000000008800e6cc002c2419262204006227a8c1a47c242e70a7" -> null
smartmeter.0 | 2023-10-11 15:07:38.055 | debug | ADD NEW DATA (2393 + NEW 1)
smartmeter.0 | 2023-10-11 15:07:38.053 | debug | MATCH-RESULT MESSAGE: "773180a67564ae78fc627d8d750265a2c1ff7bb4443d04aec0dc20d502652006a6c4ff00e60080d5b800800088882495c10000132188761601f020001008f616bb03000088802a44984085008098000100008c20a2890028241120260400220080049f4402a00094dc7705ff773180442d80aa18dc407d08740265a2c1e723b0e42524aec0fc203502650082a2c16600a60040d598008000048c2095c00000172588561601f02204908876163b8e00040c802a44984000c0009800010400cc00a68d002424112022000022008003e4fd23a00480e23700ff773180a43520aa38fc407f88d50645a2c1efbfb4443d2406c0dc21d592650082a2c1ef22e60080379800804400882415c0200056756765494504f420041088f612bb0c000088806e44984000400098004000008822e6cc006c24190026000022004004443523a0cc00047717f9770380243d20ee38dc407f8d774665a6c4e77734442420aae2dc01d406650082a2c1e700e60000d498008000008800aac1000013212076560174220410887616bfe3000008802a11980000000098000000008c00a68d002c24ed0022600022004081e42d006e107f0c7745fe7731c04424205218dc627d8d750275e6c1ee0fb0442c24aa60dc207706750056a6c4ef22a60080239800800080882095c10000172548f61201702000b888f6123e8d200088802a14980005000098000000008800e6cc0028241922262000220080b14434202a30bf8c7700ff773180443d24aa18dc407d88f50655a2c1f79bb0443564aec0dc357502650086a2c4f700a20080d59800800080882095c10000132488761204f4000490085656bf82000088802e449800900000b8000100488c00a60d006c24e50026000022001408447d242e102b247785e7771180447564ae18dc407f883606650a64f680c5e42c20aec0dc207502652286a2c17700a20400f59c00800000882495c12000172560f616017022041008f612bb8f00008884224498000000009c000100008c00a60d002824e500220000220080b44475646e10738c2380f8773180442d24ae18dc407f88350665a223f723b0e67564ee60dc217402650086a2c1f726220000d59800800004880095c0000013219c561201f42200108876123fe8980004000824040002cc00f82015880480d8000e20002824d900220000220114c3443c20026680713785ff773180443524ae18dc20318d230265a6c47feff4447d24aec0dc20d5024500d6a6617f00260480d49c00800000882495610000172588f616a37020001008f612bfc60044cc802e449840000088980000c0008820a2890028261920220004220080024445242e10bf283780f9771180444d20aa187e403188750245a2c1c7f7b444452002c0dc00d402652006a621c700260080d59c00800000882095c120001321207616e7e098448510607612bb05000088802e449844050088f8000004008c00a6cc006c24e500662200220080089fc506240c00047717b4893180e655642e18dc407388750265e6c44f6bb4445d20aac0dc207506750086e6c1ce20a60080749800804000882495630000132488f63601f426041088f612bb980044000824040006000cf826018cc08000a60d002824d90066600022011482449503a4886c157717fa971180a45d24aa18dc607388d50645a2c1c72360444524aec0dc00d406450086a2c1c700260080d59800800004882095c020001371e761550501f0220010887612bb8320048c802e44980080000098000100008800a28d002c2411202200008a0000c0445d646e1063dc9700f1771380264524aa18dc40718d77026502c4cfeb34444c20aa62fe01d402650086a2c1ce00a20080d59800800000886415e12000172188f61201f420041088f612bb8f0000cc802a1598000500009c000000008800e6cc00282419002200002200001d9f440902630555771799770180445423a08088407100d50265a6c1d637b4e45420ae62dc01f506750082a6c4d700a60040d59c00c00080e02095c1220017219c76d5fc01f42000108876d57c0d98c0040008240420064000f800010c008000a68d002024112626000022008007445c202a10378c7700fd7731c04445240218dc627388f50265a2c1df5774444d20aec0dc20f5026522d6a6c15700a20080d598008000008820d5c12200162588f6d5fc01f420001088f6d5786d0820048880224498000000009c000104008c00a60d04282425262200000a0000b4a445242e102b887705fc771180444d24aa18dc4073887502650661d737b4445500aac0dc217546450082a662d720a6048475f8008000008820d5c1000013218876b3fc01f02204d08876f57c6d81000088802a44984400000098000004008800e68c00202419002200040a008003e45d242e103b887785f37731804455240218dc627588d4c6155d88f661079bc41b4667dc217402450082e663df00a60080d59800800080882495c10000162188f6f5fca2702204108856d5784db100048c8026449800900404b80000004c882022890028771100260000220028814445042e1063087705fd773180444c20aa18dc40750dd40265a2c1c7b7b0e44524aec0dc20d5067500d6a2c1c700a24480d59800800000a064d5c100001321087649f801f4988080b8887649784d8a00048c802e4498000000009800010000cc22a28d002c241122660000220000c1444d242a10f7887785fb771180447420aa18fe40358d760265a2c1cf2bf4445d04aec0dc20d50265008626e1cf00260080d5f8008000c87344a0110000172588f649f8a1f02200b888f649784d6000040c842a44980005000098440100408c00a609002c24d10066000022008007445464566680013717fb773180445d24aac08866778d770665a2c1c7e3b4446504aec0dc35d50205208222c1c600a60080d5b800800088882095c00000132108764974a1f0200010207649784d0700048cc02e44984005009c7f00000c0084002289002824190026000022010005446d202e10f3887745eb77038044e50623678bdc407508770265a663cf37b0446d24aec0fe002302652082a6c14720a60084d59c00800000882095c10000132560f649f801f42000109cf649744d880000cc806e44b80005cc00f8000004008800a2cc002c241100220440220080c2e675202e6680847717e1373180e47c20ae18dc60758dd4026522c1d7ebb0447520aac0dc20d5024500d6a661d700a20080d59800800000e4209563200016218876c9f801f0220410887649784ce20044cc802e44d80000440098000000008800e6cc002c2419262204006227a8c1a47c242e70" -> null
smartmeter.0 | 2023-10-11 15:07:38.052 | debug | ADD NEW DATA (2392 + NEW 1)

</body>
</html>`

Ohne Debug, also das Normale Protokoll:

`2023-10-10 08:39:59.698 - info: smartmeter.0 (6232) List of port: [{"path":"/dev/ttyAMA0"},{"path":"/dev/ttyS0"}]
2023-10-10 08:40:24.864 - info: smartmeter.0 (6232) Got terminate signal TERMINATE_YOURSELF
2023-10-10 08:40:24.871 - info: smartmeter.0 (6232) terminating
2023-10-10 08:40:24.877 - info: smartmeter.0 (6232) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2023-10-10 08:40:25.382 - info: smartmeter.0 (6232) terminating
2023-10-10 08:40:34.983 - info: smartmeter.0 (6252) starting. Version 3.3.4 in /opt/iobroker/node_modules/iobroker.smartmeter, node: v16.19.1, js-controller: 5.0.12
2023-10-10 08:42:35.113 - info: smartmeter.0 (6252) Error: No or too long answer from Serial Device after last request.
2023-10-10 08:42:35.119 - warn: smartmeter.0 (6252) No or too long answer from Serial Device after last request.`

![image](https://github.com/Apollon77/ioBroker.smartmeter/assets/31133588/081f5299-8ea0-413b-89d5-ed1aecec343e)
![image](https://github.com/Apollon77/ioBroker.smartmeter/assets/31133588/4fdbc3d3-035c-40c7-b103-a7ee51b901f9)

**Comment by Apollon77** [comment]
Am besten die Frage bitte im Forum Thread stellen. Spontan machen die reinkommenden Daten keinen Sinn bzw sind komisch. Spontan könnte der Kopf verrutscht sein oder so. Forum und Community brain hat bestimmt mehr Ideen.

**Comment by Hilti23** [comment]
Ich mache das Ticket noch mal auf, falls jemand anders auch das Problem hat.
Nach einem downgrade des JS Controllers auf 4.0.2.4 geht auch der Smartmeter wieder...

![image](https://github.com/Apollon77/ioBroker.smartmeter/assets/31133588/8524fada-fb15-4493-a43b-7d872cfc6f79)

**Comment by Apollon77** [comment]
ääähhmm ... sorry aber nee das eine kann mit dem anderen nichts zu tun haben
