### ISSUE TITLE
DWS74 not all data Points

### ISSUE THREAD

**Issue by Danielnope** [Apollon77/ioBroker.smartmeter#388]
DWS74, only the data points 
- 1-0:16_7_0__255
- 1-0:1_8_0__255
- 1-0_96_1_0__255
- 1-0:96_50_1__1
 are displayed.

 The pin protection in the meter is deactivated and the info display is on.

my adapter configuration is

data protocol:  Smart Message Language
Seriel device: standart protocol
coding SML:  Binärdada (standard)

I have already tested several different configurations. If I read the meter with a PC tool I get all the information.

**Comment by Apollon77** [comment]
If omly these data are in the objects, only these data are provided in the SML ... You can turn on debug logging to verify. Else for support on how to solve this please check in forum
