### ISSUE TITLE
efr SGM-D4-A920N

### ISSUE THREAD

**Issue by Schnietz** [Apollon77/ioBroker.smartmeter#402]
Hi, 

gibt es eine Möglichkeit den "efr SGM-D4-A920N" auszulesen ? Hatte Jahrelang einen Iskra Zähler und es lief ohne Probleme. Nun werden bei uns überall die "efr" eingebaut. Leider ist er nicht gelistet und Informationen wie er ausgelesen wird sind dürftig. 

Danke fürs lesen,

Gruß, Markus

**Comment by Apollon77** [comment]
Welche Einstellungen wurden genutzt=? was steht im Log? Ich hab das gefunden? passt das zu deinem Handbuch?

https://www.photovoltaikforum.com/thread/164008-z%C3%A4hler-efr-sgm-c4-ich-bekommen-ihn-nicht-zum-laufen/

gehen diese EInstellungen? Hast Du eine PIN bekommen und die freigschaltet? Oder ist es HTTP?

Ohne mehr informationen kann ich daz unichts sagen

**Comment by Schnietz** [comment]
Ich war einfach zu doof und überschnell.

 Tut mir leid, läuft jetzt. Falsche Einstellung.

**Comment by andye2** [comment]
Hi @Schnietz,

Ich habe jetzt auch diesen Zähler erhalten, bekomme aber leider auch nur ein paar Grunddaten geliefert. Kannst du mir sagen, was du eingestellt hast, damit auch die aktuellen Werte ausgelesen werden?
Viele Grüsse Andy

PS: habs gelöst, man musste beim Zähler INF auf on stellen um den kompletten Datensatz zu erhalten.
