### ISSUE TITLE
AS1440 Invalid OBIS String

### ISSUE THREAD

**Issue by joerghildering** [Apollon77/ioBroker.smartmeter#51]
The Log in iobroker says: 
"Error while parsing D0 content: ignore complete part Error: Invalid Obis String 1-1:30D"
"Error while parsing D0 content: ignore complete part Error: Invalid Obis String 1-1:7D"
"Error while parsing D0 content: ignore complete part Error: Invalid Obis String 1-1:1D"
Could you please add this? Thanks

**Comment by Apollon77** [comment]
Please provide debug log from adapter that I can der full response from smartmeter. The obis ids seems really invalid.

**Comment by Apollon77** [comment]
No reaction ... close
