### ISSUE TITLE
Smartmeter Grid-Hub

### ISSUE THREAD

**Issue by HeiLuRa** [Apollon77/ioBroker.smartmeter#64]
[https://forum.iobroker.net/topic/27116/test-adapter-smartmeter-3-0-x/94](url)

**Comment by Apollon77** [comment]
Jupp, ich denke es gibt hier den Fall das der HTTP Request nicht erfolgreich ist und dann das neue Starten hängt ... Ich schaue das ich es in der nächsten version fixe

**Comment by Apollon77** [comment]
Bitte 3.0.10 versuchen. GitHub oder ab morgen im Latest
