### ISSUE TITLE
Please remove colons from object names

### ISSUE THREAD

**Issue by cronus6387** [Apollon77/ioBroker.smartmeter#74]
I tried to connect my Loxone miniserver with the smartmeter over the simple API. Because of colons in the object names this is not possible. Please can you adjust the following line of the smartmeter.js in futur versions:

(line 361) let ioChannelId = obisResult[obisId].idToString().replace(/[\]\[*,;'"`<>\\?]/g, '__');

to 

(line 361) let ioChannelId = obisResult[obisId].idToString().replace(/[\]\[*,;:'"`<>\\?]/g, '__');

**Comment by Apollon77** [comment]
This would be a hard breaking change for all users and so I decided not to do that. Colons are officially allowed characters for state ids. If other adapters have problems with it they should handle it on their side. 

Alternatively you can use aliasses with js-Controller 2.x to easiely map to a object if without colons. 

Sorry, but I will not change this in this adapter.
