### ISSUE TITLE
No objects are created

### ISSUE THREAD

**Issue by hacki11** [Apollon77/ioBroker.smartmeter#80]
Smartmeter (Holley) responds with SML messages with incorrect CRC. Smartmeter decodes the messages (1.8.0, etc.) correctly but no objects are created.

iobroker 2.2.7
smartmeter 3.0.10
CRC mismatch ignore = true

Log https://pastebin.com/W64K3CaQ

perhaps the issue lies around these lines of code
https://github.com/Apollon77/smartmeter-obis/blob/45aa131c92d4e491ebb384e583a26d50d1c6f812/lib/protocols/SmlProtocol.js#L87

**Comment by hacki11** [comment]
Seems there are two CRC values, the smartmeter-obis only ignores the outer crc

// we ignore whole-Message CRC (smlFile.valid;) only check detail CRCs

**Comment by Apollon77** [comment]
I prepare a patch

**Comment by Apollon77** [comment]
Please try 3.1.0 ... comes to latest soon (or use GitHub version)
